version: '3.0'
services:
  swift:
    container_name: swift
    build:
      context: ./swift
      args:
        xdebug_host: ${XDEBUG_HOST}
    extra_hosts:
      kayako-dev: ${GWIP}
    ports:
     - "80:80"
    volumes:
     - ${CODE_PATH}:/var/www/swift
     - ${JOOMLA}:/var/www/joomla
     - ${DRUPAL}:/var/www/drupal
     - ${MAGENTO}:/var/www/magento
     - ${WORDPRESS}:/var/www/wordpress
     - ${OAUTH2}:/var/www/oauth2
     - ${WHMCS}:/var/www/whmcs
    environment:
      PHP_IDE_CONFIG: "serverName=default"
    networks:
      - default
      - aladdin_default
    external_links:
      - aladdin_db_1

networks:
  aladdin_default:
    external: true
