version: '3.0'

services:
  swift:
    build:
      dockerfile: Dockerfile
      context: ./swift
      args:
       - "USER=${USER}"
    extra_hosts:
      maint: ${GWIP}
      maint.xo.local: ${GWIP}
      mail.xo.local: ${GWIP}
    ports:
     - "8080:80"
     - "4343:443"
    volumes:
     - ./swift/kayako-SWIFT/trunk:/var/www/html
     - /home/wgarcia:/home/wgarcia
    environment:
      PHP_IDE_CONFIG: "serverName=default"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG}"
      LINES: ${LINES}
      COLUMNS: ${COLS}
      TERM: linux
    external_links:
      - db:mysql
    networks:
      aladdin_default:
      default:

networks:
  aladdin_default:
    external: true
