version: '3.0'
services:
  swift:
    container_name: swift
    build:
      dockerfile: Dockerfile
      context: ./swift
    extra_hosts:
      kayako-dev: ${GWIP}
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ${CODE_PATH}:/home/swift
     - /home/wgarcia/kayako:/home/kayako
    environment:
      PHP_IDE_CONFIG: "serverName=default"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=192.168.0.20 remote_enable=1 remote_autostart=1"
      LINES: ${LINES}
      COLUMNS: ${COLS}
      TERM: linux
    links:
      - mysql

  mysql:
    image: "mysql:5.7"
    container_name: mysql
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: OGYxYmI1OTUzZmM
      MYSQL_DATABASE: swift
      MYSQL_USER: root
      MYSQL_PASSWORD: OGYxYmI1OTUzZmM
    ports:
     - "3306:3306"
