version: '3.0'
volumes:
  database:

services:
  swift:
    build:
      dockerfile: Dockerfile
      context: ./swift
    extra_hosts:
      kayako-dev: ${GWIP}
      swift.kayako-dev.local: ${GWIP}
      mail.kayako-dev.local: ${GWIP}
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./swift/kayako-SWIFT/trunk:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=default"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG}"
      LINES: ${LINES}
      COLUMNS: ${COLS}
      TERM: linux
    links:
      - mysql

  mysql:
    image: "mysql:5.7"
    volumes:
     - database:/var/lib/mysql
     - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: OGYxYmI1OTUzZmM
      MYSQL_DATABASE: swift
      MYSQL_USER: root
      MYSQL_PASSWORD: OGYxYmI1OTUzZmM
    ports:
     - "3306:3306"
