version: '3.0'
services:
  swift:
    build:
      context: ./swift
      args:
        xdebug_host: ${XDEBUG_HOST}
    ports:
     - "80:80"
    volumes:
     - ${CODE_PATH}:/var/www/html/classic
    environment:
      PHP_IDE_CONFIG: "serverName=default"
